version: '2'
services:
    model:
        container_name: DeepMushroom
        build: ./service/web
        command: gunicorn --bind 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        volumes:
            - /model:/usr/src/app/web_inference/model
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
