version: '2'
services:
    model:
        container_name: DeepMushroom
        build: .
        ports:
            - "5000:5000"
        volumes:
            - /model:/app/app/model
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
